export enum ErrorCode {
  CONFIG_MISSING_APP_ID = "CONFIG_MISSING_APP_ID",
  CONFIG_INVALID_ENV = "CONFIG_INVALID_ENV",
  CONFIG_INVALID_LOG_LEVEL = "CONFIG_INVALID_LOG_LEVEL",
  SDK_ALREADY_INITIALIZED = "SDK_ALREADY_INITIALIZED",
  CONSENT_INVALID_STATE = "CONSENT_INVALID_STATE",
  API_CLIENT_ERROR = "API_CLIENT_ERROR",
  API_UNAUTHORIZED = "API_UNAUTHORIZED",
  API_TIMEOUT = "API_TIMEOUT",
  API_NETWORK_ERROR = "API_NETWORK_ERROR",
  INVALID_BACKEND_RESPONSE = "INVALID_BACKEND_RESPONSE",
}

export interface BaseelErrorPayload {
  code: ErrorCode;
  message: string;
  details?: any;
}
